name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.10
  cloudinary_public: ^0.20.0
  flutter_rating_bar: ^4.0.1
  pay: ^1.1.1
  intl: ^0.17.0
  fl_chart: ^0.62.0
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  speech_to_text: ^6.1.1
  image_picker: ^0.8.7+5
  flutter_launcher_icons: "^0.13.1"
  dialog_flowtter: ^0.3.3
  razorpay_flutter: ^1.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
